.github/workflows/terraform-dev.yml

This is a first pass to test the triggering of a github action ruining a terraform plan action against the sandbox env

Create terraform-dev.yml for dev terraform plan action

---

.github/workflows/terraform-dev.yml

Ordering change of yaml conditions to test triggering of the action

Update terraform-dev.yml 

---

infrastructure/lambda-search-doc-references.tf

remove env var and permissions for s3 buckets in search doc lambda

[PRMDR-95] - update lambda for lloyd george search

---

infrastructure/buckets.tf
infrastructure/variable.tf

Adding new bucket to store zip files requested by a user

[PRMDR-213]

---

.github/workflows/terraform-deploy-feature-to-sandbox-with-dispatch.yml
.github/workflows/terraform-destroy-dev-environments-cron.yml
.github/workflows/terraform-destroy-test-environments-cron.yml

…loy on merge completion, added new deployt to sandbox with dispatch job to trigger second repo deploys.

PRMDR_128: Cron Actions

---

bootstrap/README.md
infrastructure/README.md
infrastructure/lambda-document-manifest-by-nhs-number.tf

SUBTASK 110 - lambda for document manifest by nhs number

---

infrastructure/README.md
infrastructure/buckets.tf
infrastructure/lambda-bulk-upload-metadata.tf
infrastructure/modules/ecr/main.tf
infrastructure/modules/lambda/README.md
infrastructure/modules/lambda/main.tf
infrastructure/modules/lambda/variable.tf
infrastructure/modules/sqs/README.md
infrastructure/modules/sqs/main.tf
infrastructure/modules/sqs/variable.tf
infrastructure/queues.tf
infrastructure/variable.tf

Prmdr 334 story (PRMDR-336 only)

---

virusscanner/README.md
virusscanner/terraform/dev.s3.tfbackend
virusscanner/terraform/dev.tfvars
virusscanner/terraform/main.tf
virusscanner/terraform/notifications.tf
virusscanner/terraform/pre-prod.s3.tfbackend
virusscanner/terraform/pre-prod.tfvars
virusscanner/terraform/prod.s3.tfbackend
virusscanner/terraform/prod.tfvars
virusscanner/terraform/variables.tf

Added infra code for Virus Scanner
Reviews welcome as I write the Readme

PRMDR-362 virus Scanner Infrastructure

---

infrastructure/modules/ecs/lb.tf

Adding load balancer deletion protection as per feedback from pentest

[PRMDR-455]

---

infrastructure/README.md
infrastructure/buckets.tf
infrastructure/ecs.tf
infrastructure/main.tf
infrastructure/modules/ecs/README.md
infrastructure/modules/ecs/lb.tf
infrastructure/modules/ecs/variable.tf

Create new Access Logs Bucket
Create Bucket Policy, and attach to logs bucket
Update Load Balancer Terraform to enable access logs and provide bucket id
Co-authored-by: RachelHowellNHS <rachel.howell6@nhs.net>

[PRMDR-457] Configure access logging on the load balancer

---

infrastructure/README.md
infrastructure/dynamo_db.tf
infrastructure/lambda-bulk-upload-report.tf
infrastructure/lambda-bulk-upload.tf
infrastructure/modules/dynamo_db/README.md
infrastructure/modules/dynamo_db/main.tf
infrastructure/modules/dynamo_db/variable.tf
infrastructure/modules/ecs/variable.tf
infrastructure/variable.tf

- set up Point in time recovery for 3 dynamodb tables:  ARF, LG, BulkUpload Report

PRMDR-503 Dynamo table Point in time recovery

---

infrastructure/README.md
infrastructure/api.tf
infrastructure/lambda-bulk-upload.tf
infrastructure/modules/lambda/README.md
infrastructure/modules/lambda/main.tf
infrastructure/modules/lambda/variable.tf
infrastructure/variable.tf
virusscanner/terraform/README.md

- Put a max concurrency limit of 5 to bulk upload lambda

PRMDR-517  Address 429 'Too Many Requests' response from PDS

---

infrastructure/modules/dynamo_db/main.tf

add dynamodb:BatchWriteItem in dynamo table

[PRMDR-518]

---

infrastructure/README.md
infrastructure/lambda-send-feedback.tf
infrastructure/modules/ses/README.md
infrastructure/modules/ses/main.tf
infrastructure/modules/ses/output.tf
infrastructure/modules/ses/variable.tf
infrastructure/ses.tf
infrastructure/variable.tf

Reverts nhsconnect/national-document-repository-infrastructure#135

Revert "[FIX] PRMDR-599: Add auto-verification and enable test environment"

---

infrastructure/api.tf
infrastructure/buckets.tf
infrastructure/lambda-back-channel-logout.tf
infrastructure/lambda-create-doc-ref.tf
infrastructure/lambda-delete-doc-ref.tf
infrastructure/lambda-document-manifest-by-nhs-number.tf
infrastructure/lambda-lloyd-george-record-stitch.tf
infrastructure/lambda-login-redirect.tf
infrastructure/lambda-logout.tf
infrastructure/lambda-search-doc-references.tf
infrastructure/lambda-search-patient.tf
infrastructure/lambda-token.tf
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/variable.tf

Updating Params/logic for Production URL deployment "national-document-repository.nhs.uk"
Certificate and Hosted Zone already exist in Prod AWS Account

Rich url prod update

---

infrastructure/lambda-create-doc-ref.tf
infrastructure/modules/app_config/main.tf

Add IAM policy for deleting incomplete upload files in Lloyd George s3 bucket

PRMDR-743 - Lambda: Update Create Document Reference Lambda Access Checks

---

infrastructure/README.md
infrastructure/lambda-create-doc-ref.tf
infrastructure/lambda-update-upload-state.tf
infrastructure/lambda-upload-confirm-result.tf
infrastructure/lambda-virus-scan-result.tf
infrastructure/modules/app_config/configurations/2024-05-21-prod.json

Reverts nhsconnect/national-document-repository-infrastructure#183

Revert "PRMDR-0000: v1.4.0 release fixes"

---

infrastructure/modules/app_config/configurations/dev.json
infrastructure/modules/app_config/configurations/pre-prod.json
infrastructure/modules/app_config/configurations/prod.json

add new feature flag for ods report download

[PRMP-1551] add new feature flag for ods report download

---

infrastructure/lambda-bulk-upload.tf
infrastructure/lambda-pdf-stitching.tf

Reverts nhsconnect/national-document-repository-infrastructure#252

[PRMP-1594] Revert [PRMP-1512] BulkUploadLambda - On Success changes

---

infrastructure/backups.tf
infrastructure/modules/app_config/main.tf

Terraform plans now much reduced to only required changes.

[NDR-60] Tidy up Terraform plan and unneeded applys

---

.github/workflows/terraform-dev-to-main-ci.yml

[Report for environment: ndr-dev](https://github.com/nhsconnect/national-document-repository-infrastructure/pull/294#issuecomment-2857733246)
Above comment is the correct comment to look at, other 3 were from testing.

[NDR-56] Add Terraform plan comment on PRs

---

.github/workflows/terraform-daily-healthcheck-deploy-and-destroy.yml
.github/workflows/terraform-deploy-feature-to-sandbox-with-dispatch.yml
.github/workflows/terraform-deploy-feature-to-sandbox.yml
.github/workflows/terraform-deploy-to-perf-manual.yml
.github/workflows/terraform-deploy-to-pre-prod-manual.yml
.github/workflows/terraform-deploy-to-prod-manual.yml
.github/workflows/terraform-deploy-to-test-manual.yml
.github/workflows/terraform-deploy-virus-scanner.yml
.github/workflows/terraform-destroy-dev-environments-cron.yml
.github/workflows/terraform-destroy-environment-manual.yml
.github/workflows/terraform-destroy-test-environments-cron.yml
.github/workflows/terraform-dev-to-main-ci.yml

Update all pipelines to use the latest version of Terraform.

[NDR-69] Update Terraform version to 1.11.4

---

.github/workflows/terraform-daily-healthcheck-deploy-and-destroy.yml

Implemented potential fix for cypress tests on daily run, also added browser version on screenshots and videos

[PRM-322] Fix cypress tests on daily run

---

infrastructure/iam.tf

Add permission to access all S3 folder instead of just combined folder
https://nhsd-jira.digital.nhs.uk/browse/PRMT-70

[PRMT-70] Improve efficiency of LG retrieval

---

infrastructure/lambda-bulk-upload.tf

Bulk upload sandbox ingestion defaulted to true
https://nhsd-jira.digital.nhs.uk/browse/PRMT-537

[PRMT-537] Bulk upload lambda enabled on sandboxes
